### ISSUE TITLE
Feature Request: Web Streaming Audio

### ISSUE THREAD

**Issue by hpssjellis** [Seeed-Studio/ModelAssistant#165]
Hi @LynnL4 can you make a suggestion for which repository I would put this feature request.

Feature Request: Web Streaming audio.

Like the XIAO esp32s3 Camera streaming webpage does seeedstudio have Arduino code for a streaming audio webpage?

Better yet can the streaming audio be done at the same time as the streaming visual all on the same webpage?  Probably not but I thought I would ask.

Jeremy

**Comment by LynnL4** [comment]
Hello, yes, these are the key features we are focusing on for Q1 this year, including audio, sensor data collection, and deployment.

- Better yet can the streaming audio be done at the same time as the streaming visual all on the same webpage? Probably not but I thought I would ask.
Regarding this issue, it might not be feasible due to bandwidth constraints, but we will attempt to look into it.
